// Generated by gencpp from file begin_tutorial/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGIN_TUTORIAL_MESSAGE_ADDTWOINTS_H
#define BEGIN_TUTORIAL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <begin_tutorial/AddTwoIntsRequest.h>
#include <begin_tutorial/AddTwoIntsResponse.h>


namespace begin_tutorial
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace begin_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::begin_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::begin_tutorial::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::begin_tutorial::AddTwoInts > {
  static const char* value()
  {
    return "begin_tutorial/AddTwoInts";
  }

  static const char* value(const ::begin_tutorial::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::begin_tutorial::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::begin_tutorial::AddTwoInts > 
template<>
struct MD5Sum< ::begin_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::begin_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::begin_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::begin_tutorial::AddTwoIntsRequest> should match 
// service_traits::DataType< ::begin_tutorial::AddTwoInts > 
template<>
struct DataType< ::begin_tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::begin_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::begin_tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::begin_tutorial::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::begin_tutorial::AddTwoInts > 
template<>
struct MD5Sum< ::begin_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::begin_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::begin_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::begin_tutorial::AddTwoIntsResponse> should match 
// service_traits::DataType< ::begin_tutorial::AddTwoInts > 
template<>
struct DataType< ::begin_tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::begin_tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::begin_tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGIN_TUTORIAL_MESSAGE_ADDTWOINTS_H
